Revert changes to activate

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -1,11 +1,12 @@
 #!/bin/bash
 
-export PKG_CONFIG_LIBDIR=""
-export PKG_CONFIG_PATH="$(pwd)/opt/lib/pkgconfig:$(pwd)/opt/lib64/pkgconfig"
-
-if command -v module; then
-  # Jump internal use
-  module purge
-  module load gcc-9.3.0  || echo "module load gcc-9.3.0 failed"
-  module list
+if ! command -v module >/dev/null 2>&1; then
+  echo "ERROR: module command not found. This script only works inside Jump's environment."
+  return
 fi
+
+module purge
+module load gcc-9.3.0
+module load Python-3.9
+module load openssl-1.1.1s+quic1
+module list
