activate: bail if not on Jump machine
Change-Id: If2459cc92ac59e458cb70d9fb4946b3246df9bf9
Reviewed-on: https://git.firedancer.io/c/firedancer/+/140
Reviewed-by: Leopold Schabel <leo@nexantic.com>

diff --git a/activate b/activate
--- a/activate
+++ b/activate
@@ -1,6 +1,11 @@
 #!/bin/sh
 # Run jump/install-bazel to install any required dependencies before activating.
 
+if ! command -v module >/dev/null 2>&1; then
+  echo "ERROR: module command not found. This script only works inside Jump's environment."
+  return
+fi
+
 if [ ! -f ~/bin/bazel ]; then
   echo "ERROR: ~/bin/bazel does not exist. Run jump/install-bazel to install it."
   return
