Preliminary macOS support

diff --git a/src/app/frank/fd_frank_init b/src/app/frank/fd_frank_init
--- a/src/app/frank/fd_frank_init
+++ b/src/app/frank/fd_frank_init
@@ -18,8 +18,6 @@ shift 4
 CONF=tmp/$APP.cfg
 
 WKSP=$APP.wksp
-WKSP_PAGE_CNT=2
-WKSP_PAGE_SZ=gigantic
 WKSP_PERM=0600
 
 POD_SZ=16384
@@ -32,6 +30,38 @@ VERIFY_MTU=1542   # FIXME: recalibrate (probably smaller for today, larger for l
 DEDUP_TCACHE_DEPTH=4194302
 DEDUP_TCACHE_MAP_CNT=0
 DEDUP_DEPTH=$VERIFY_DEPTH
+
+# Set a sensible default for page size depending on OS and architecture platform in use;
+# Linux x64: gigantic
+# macOS x64 Intel: huge (superpages)
+# macOS ARM (M1/M2): normal
+UNAME_OUTPUT=`uname -a`
+if [[ "$UNAME_OUTPUT" == "Linux"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
+  PLATFORM_DEFAULT_WKSP_PAGE_SZ=gigantic
+elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
+  PLATFORM_DEFAULT_WKSP_PAGE_SZ=huge
+elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"arm64"* ]]; then
+  PLATFORM_DEFAULT_WKSP_PAGE_SZ=normal
+else
+  echo "Firedancer is not supported on this platform"
+  exit 1
+fi
+
+# Allow override of platform's default page size via the FD_WKSP_PAGE_SIZE environment variable.
+WKSP_PAGE_SZ=${FD_WKSP_PAGE_SIZE:-$PLATFORM_DEFAULT_WKSP_PAGE_SZ}
+
+if [ "$WKSP_PAGE_SZ" != "huge" ] && [ "$WKSP_PAGE_SZ" == "gigantic" ] && [ "$WKSP_PAGE_SZ" == "normal" ]; then
+  echo "fd_frank_init $1 $2 $3 $4: fail, invalid page size for FD_WKSP_PAGE_SIZE"
+  exit 1
+fi
+
+if [[ "$WKSP_PAGE_SZ" == "gigantic" ]]; then
+  WKSP_PAGE_CNT=2
+elif [[ "$WKSP_PAGE_SZ" == "huge" ]]; then
+  WKSP_PAGE_CNT=500
+elif [[ "$WKSP_PAGE_SZ" == "normal" ]]; then
+  WKSP_PAGE_CNT=250000
+fi    
 
 #######################################################################
 
@@ -110,4 +140,3 @@ echo ""
 
 echo success
 exit 0
-
diff --git a/src/util/shmem/fd_shmem_cfg b/src/util/shmem/fd_shmem_cfg
--- a/src/util/shmem/fd_shmem_cfg
+++ b/src/util/shmem/fd_shmem_cfg
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/bash
 
 # Use FD_SHMEM_PATH from the environment if provided for hugetlbfs mount
 # path and fallback on "/mnt/.fd" if not
@@ -6,11 +6,6 @@
 SHMEM_PATH="${FD_SHMEM_PATH:-/mnt/.fd}"
 
 ALL_TYPES="gigantic huge normal"
-
-if ! [ -x "$(command -v hwloc-calc)" ]; then
-  echo "fd_shmem_cfg: command hwloc-calc not installed, please consult README for install instructions"
-  exit 1
-fi
 
 NUMA_CNT=`hwloc-calc -N numa machine:0 2> /dev/null`
 if [ "$NUMA_CNT" = "" ]; then # Handle boxes with no NUMA
@@ -97,10 +92,21 @@ init() {
       exit 1
     fi
 
-    if grep -q $MNT_PATH /proc/mounts; then
-      echo "init $1 $2 $3: fail, internal error, mount $MNT_PATH already exists"
-      exit 1
+    if [ "$IS_LINUX_X64" == "1" ]; then
+      if grep -q $MNT_PATH /proc/mounts; then
+        echo "init $1 $2 $3: fail, internal error, mount $MNT_PATH already exists"
+        exit 1
+      fi
+    elif [ "$IS_MAC_ARM64" == "1" ] || [ "$IS_MAC_X64" == "1" ]; then
+      mount > ./mount_points
+      if grep -q $MNT_PATH ./mount_points; then
+        echo "init $1 $2 $3: fail, internal error, mount $MNT_PATH already exists"
+        rm -rf mount_points
+        exit 1
+      fi
+      rm -rf mount_points
     fi
+
     # mount point is large enough to cover the number of whole pages of
     # system DRAM (in the proc/meminfo total memory sense) for maximum
     # flexibility.  Since the pages themselves are large, the number of
@@ -108,24 +114,46 @@ init() {
     # For normal pages, we need to use a tmpfs.
     try_defrag_memory 2> /dev/null > /dev/null
     if [ "$t" = "normal" ]; then
-      mount -v -t tmpfs tmpfs $MNT_PATH
+      if [ "$IS_LINUX_X64" == "1" ]; then
+        mount -v -t tmpfs tmpfs $MNT_PATH
+      elif [ "$IS_MAC_X64" == "1" ] || [ "$IS_MAC_ARM64" == "1" ]; then
+        mount_tmpfs $MNT_PATH
+      fi
       if [ "$?" != "0" ]; then
         echo "init $1 $2 $3: fail, mount failed"
         echo "Do $0 help for help"
         exit 1
       fi
     else
-      msz=`free -b | grep Mem | awk '{ print $2 }'` # FIXME: Ugly
+      # macOS on the M1 and M2 architectures currently doesn't support superpages, so exit here
+      # if we're running on either of these platforms.
+      if [ "$IS_MAC_ARM64" ]; then
+        echo "init $1 $2 $3: fail, macOS on ARM64 (M1/M2) does not support large pages (superpages)"
+        exit 1
+      fi
+
+      if [ "$IS_LINUX_X64" == "1" ]; then
+        msz=`free -b | grep Mem | awk '{ print $2 }'` # FIXME: Ugly
+      elif [ "$IS_MAC_X64" == "1" ] || [ "$IS_MAC_ARM64" == "1" ]; then
+        msz=`sysctl hw.memsize | awk '{ print $2 }'`
+      fi
       psz=`get_page_size $t`
       msz=$((psz*(msz/psz))) # Round down to whole pages to be on safe side
-      mount -v -t hugetlbfs -o pagesize=$psz,size=$msz none $MNT_PATH
+      if [ "$IS_LINUX_X64" == "1" ]; then
+        mount -v -t hugetlbfs -o pagesize=$psz,size=$msz none $MNT_PATH
+      elif [ "$IS_MAC_X64" == "1" ]; then
+        mount_tmpfs $MNT_PATH
+      fi
+
       if [ "$?" != "0" ]; then
         echo "init $1 $2 $3: fail, mount failed"
         echo "Do $0 help for help"
         exit 1
       fi
     fi
-    try_defrag_memory 2> /dev/null > /dev/null
+    if [ "$IS_LINUX_X64" == "1" ]; then
+      try_defrag_memory 2> /dev/null > /dev/null
+    fi
   done
 
   chown -v -R $SHMEM_USER:$SHMEM_GROUP $SHMEM_PATH
@@ -204,8 +232,25 @@ alloc() {
   TYPE=$2
   NUMA=$3
 
+  # Check for cases that do not require any explicit allocation; 'normal' on all platforms,
+  # and 'huge' (superpages) on macOS.
   if [ "$TYPE" = "normal" ]; then
     echo "alloc $1 $2 $3: fail, normal pages do not require explicit allocation"
+    echo "Do $0 help for help"
+    exit 1
+  elif [ "$IS_MAC_X64" == "1" ] && [ "$TYPE" == "huge" ]; then
+    echo "alloc $1 $2 $3: fail, superpages do not require explicit allocation on macOS"
+    echo "Do $0 help for help"
+    exit 1
+  fi
+
+  # Check for options that are unsupported on the target platform.
+  if [ "$IS_MAC_ARM64" == "1" ] && ([ "$TYPE" == "huge" ] || [ "$TYPE" == "gigantic" ]); then
+    echo "alloc $1 $2 $3: fail, macOS on ARM64 (M1/M2) does not support neither superpages (hugepages) nor gigantic pages"
+    echo "Do $0 help for help"
+    exit 1
+  elif [ "$IS_MAC_X64" == "1" ] && [ "$TYPE" == "gigantic" ]; then
+    echo "alloc $1 $2 $3: fail, macOS on x64 does not support gigantic pages"
     echo "Do $0 help for help"
     exit 1
   fi
@@ -266,6 +311,18 @@ reset() {
 if [ $# -lt 1 ]; then
   echo "Commands not specified"
   echo "Do $0 help for help"
+  exit 1
+fi
+
+UNAME_OUTPUT=`uname -a`
+if [[ "$UNAME_OUTPUT" == "Linux"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
+  export IS_LINUX_X64=1
+elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
+  export IS_MAC_X64=1
+elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"arm64"* ]]; then
+  export IS_MAC_ARM64=1
+else
+  echo "Firedancer is not supported on this platform"
   exit 1
 fi
 
