Address review comments

diff --git a/src/app/frank/fd_frank_init b/src/app/frank/fd_frank_init
--- a/src/app/frank/fd_frank_init
+++ b/src/app/frank/fd_frank_init
@@ -1,8 +1,8 @@
 #!/bin/bash
 
-if [ $# -ne 4 ]; then
+if [ $# -lt 4 ]; then
   echo ""
-  echo "        Usage: $0 [APP_NAME] [APP_CORE_TARGET] [VERIFY_CNT] [BUILD]"
+  echo "        Usage: $0 [APP_NAME] [APP_CORE_TARGET] [VERIFY_CNT] [BUILD] [PAGE_SIZE]"
   echo ""
   exit 1
 fi
@@ -11,8 +11,14 @@ APP=$1
 AFFINITY=$2
 VERIFY_CNT=$3
 BUILD=$4
-shift 4
-
+if [ -z "$5" ]; then
+  WKSP_PAGE_SZ=""
+  shift 4
+else
+  WKSP_PAGE_SZ=$5
+  shift 5
+fi
+  
 #######################################################################
 
 CONF=tmp/$APP.cfg
@@ -35,32 +41,43 @@ DEDUP_DEPTH=$VERIFY_DEPTH
 # Linux x64: gigantic
 # macOS x64 Intel: huge (superpages)
 # macOS ARM (M1/M2): normal
-UNAME_OUTPUT=`uname -a`
-if [[ "$UNAME_OUTPUT" == "Linux"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
+OS_STR=`uname -s`
+ARCH_STR=`uname -m`
+if [[ "$OS_STR" == "Linux" ]] && [[ "$ARCH_STR" == "x86_64" ]]; then
   PLATFORM_DEFAULT_WKSP_PAGE_SZ=gigantic
-elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
-  PLATFORM_DEFAULT_WKSP_PAGE_SZ=huge
-elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"arm64"* ]]; then
-  PLATFORM_DEFAULT_WKSP_PAGE_SZ=normal
+elif [[ "$OS_STR" == "Darwin" ]] && [[ "$ARCH_STR" == "x86_64" ]]; then
+  VERSION_LEVEL_STR=`uname -v`
+  if [[ "$VERSION_LEVEL_STR" == *"ARM64"* ]]; then
+    PLATFORM_DEFAULT_WKSP_PAGE_SZ=normal
+  else
+    PLATFORM_DEFAULT_WKSP_PAGE_SZ=huge
+  fi
+elif [[ "$OS_STR" == "Darwin" ]] && [[ "$ARCH_STR" == "arm64" ]]; then
+  echo "Run firedancer under Rosetta on macOS M1 and M2 systems"
+  exit 1
 else
   echo "Firedancer is not supported on this platform"
   exit 1
 fi
 
-# Allow override of platform's default page size via the FD_WKSP_PAGE_SIZE environment variable.
-WKSP_PAGE_SZ=${FD_WKSP_PAGE_SIZE:-$PLATFORM_DEFAULT_WKSP_PAGE_SZ}
+# Allow override of platform's default page size via a command line argument
+# If PAGE_SIZE argument was not provided at the command line, use the platform's default,
+# as determined above.
+if [[ -z "$WKSP_PAGE_SZ" ]]; then
+  WKSP_PAGE_SZ=$PLATFORM_DEFAULT_WKSP_PAGE_SZ
+fi
 
-if [ "$WKSP_PAGE_SZ" != "huge" ] && [ "$WKSP_PAGE_SZ" == "gigantic" ] && [ "$WKSP_PAGE_SZ" == "normal" ]; then
-  echo "fd_frank_init $1 $2 $3 $4: fail, invalid page size for FD_WKSP_PAGE_SIZE"
+if [ "$WKSP_PAGE_SZ" != "huge" ] && [ "$WKSP_PAGE_SZ" != "gigantic" ] && [ "$WKSP_PAGE_SZ" != "normal" ]; then
+  echo "fd_frank_init fail, invalid page size '$WKSP_PAGE_SZ' specified"
   exit 1
 fi
 
 if [[ "$WKSP_PAGE_SZ" == "gigantic" ]]; then
   WKSP_PAGE_CNT=2
 elif [[ "$WKSP_PAGE_SZ" == "huge" ]]; then
-  WKSP_PAGE_CNT=500
+  WKSP_PAGE_CNT=1024
 elif [[ "$WKSP_PAGE_SZ" == "normal" ]]; then
-  WKSP_PAGE_CNT=250000
+  WKSP_PAGE_CNT=524288
 fi    
 
 #######################################################################
diff --git a/src/util/shmem/fd_shmem_cfg b/src/util/shmem/fd_shmem_cfg
--- a/src/util/shmem/fd_shmem_cfg
+++ b/src/util/shmem/fd_shmem_cfg
@@ -97,7 +97,7 @@ init() {
         echo "init $1 $2 $3: fail, internal error, mount $MNT_PATH already exists"
         exit 1
       fi
-    elif [ "$IS_MAC_ARM64" == "1" ] || [ "$IS_MAC_X64" == "1" ]; then
+    elif [ "$IS_MAC_M1_M2" == "1" ] || [ "$IS_MAC_X64" == "1" ]; then
       mount > ./mount_points
       if grep -q $MNT_PATH ./mount_points; then
         echo "init $1 $2 $3: fail, internal error, mount $MNT_PATH already exists"
@@ -116,7 +116,7 @@ init() {
     if [ "$t" = "normal" ]; then
       if [ "$IS_LINUX_X64" == "1" ]; then
         mount -v -t tmpfs tmpfs $MNT_PATH
-      elif [ "$IS_MAC_X64" == "1" ] || [ "$IS_MAC_ARM64" == "1" ]; then
+      elif [ "$IS_MAC_X64" == "1" ] || [ "$IS_MAC_M1_M2" == "1" ]; then
         mount_tmpfs $MNT_PATH
       fi
       if [ "$?" != "0" ]; then
@@ -127,14 +127,14 @@ init() {
     else
       # macOS on the M1 and M2 architectures currently doesn't support superpages, so exit here
       # if we're running on either of these platforms.
-      if [ "$IS_MAC_ARM64" ]; then
-        echo "init $1 $2 $3: fail, macOS on ARM64 (M1/M2) does not support large pages (superpages)"
+      if [ "$IS_MAC_M1_M2" ]; then
+        echo "init $1 $2 $3: fail, macOS on M1/M2 does not support large pages (superpages)"
         exit 1
       fi
 
       if [ "$IS_LINUX_X64" == "1" ]; then
         msz=`free -b | grep Mem | awk '{ print $2 }'` # FIXME: Ugly
-      elif [ "$IS_MAC_X64" == "1" ] || [ "$IS_MAC_ARM64" == "1" ]; then
+      elif [ "$IS_MAC_X64" == "1" ] || [ "$IS_MAC_M1_M2" == "1" ]; then
         msz=`sysctl hw.memsize | awk '{ print $2 }'`
       fi
       psz=`get_page_size $t`
@@ -245,7 +245,7 @@ alloc() {
   fi
 
   # Check for options that are unsupported on the target platform.
-  if [ "$IS_MAC_ARM64" == "1" ] && ([ "$TYPE" == "huge" ] || [ "$TYPE" == "gigantic" ]); then
+  if [ "$IS_MAC_M1_M2" == "1" ] && ([ "$TYPE" == "huge" ] || [ "$TYPE" == "gigantic" ]); then
     echo "alloc $1 $2 $3: fail, macOS on ARM64 (M1/M2) does not support neither superpages (hugepages) nor gigantic pages"
     echo "Do $0 help for help"
     exit 1
@@ -314,13 +314,20 @@ if [ $# -lt 1 ]; then
   exit 1
 fi
 
-UNAME_OUTPUT=`uname -a`
-if [[ "$UNAME_OUTPUT" == "Linux"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
+OS_STR=`uname -s`
+ARCH_STR=`uname -m`
+if [[ "$OS_STR" == "Linux" ]] && [[ "$ARCH_STR" == "x86_64" ]]; then
   export IS_LINUX_X64=1
-elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"x86_64"* ]]; then
-  export IS_MAC_X64=1
-elif [[ "$UNAME_OUTPUT" == *"Darwin"* ]] && [[ "$UNAME_OUTPUT" == *"arm64"* ]]; then
-  export IS_MAC_ARM64=1
+elif [[ "$OS_STR" == "Darwin" ]] && [[ "$ARCH_STR" == "x86_64" ]]; then
+  VERSION_LEVEL_STR=`uname -v`
+  if [[ "$VERSION_LEVEL_STR" == *"ARM64"* ]]; then
+    export IS_MAC_M1_M2=1
+  else
+    export IS_MAC_X64=1
+  fi
+elif [[ "$OS_STR" == "Darwin" ]] && [[ "$ARCH_STR" == "arm64" ]]; then
+  echo "Run firedancer under Rosetta on macOS M1 and M2 systems"
+  exit 1
 else
   echo "Firedancer is not supported on this platform"
   exit 1
