Preserve +t permissions on normal page sandbox directory
Change-Id: I5dc9a8d37f14390025a429a0837fdeceffa1b1b3

diff --git a/src/util/shmem/fd_shmem_cfg b/src/util/shmem/fd_shmem_cfg
--- a/src/util/shmem/fd_shmem_cfg
+++ b/src/util/shmem/fd_shmem_cfg
@@ -137,6 +137,13 @@ init() {
     exit 1
   fi
 
+  chmod -v +t $SHMEM_PATH/.normal
+  if [ "$?" != "0" ]; then
+    echo "init $1 $2 $3: fail, chmod failed"
+    echo "Do $0 help for help"
+    exit 1
+  fi
+
   echo init $1 $2 $3: success
 }
 
