waltz: add test_ip to CI
- Early exits test_ip if capabilities are insufficient
- Checks the output of test_ip_dump routing tables

diff --git a/src/waltz/ip/test_ip b/src/waltz/ip/test_ip
--- a/src/waltz/ip/test_ip
+++ b/src/waltz/ip/test_ip
@@ -17,7 +17,11 @@ CONF=tmp/test_arp.conf
 
 ########################################################################
 
-if [ $# -ne 1 ]; then
+if [[ "$(realpath $0)" =~ "/build/" ]]; then
+  UNIT_TEST=$(dirname $0)
+elif [[ $# == 1 ]]; then
+  UNIT_TEST=$1/unit-test
+else
   echo ""
   echo "        build directory not specified"
   echo ""
@@ -28,8 +32,6 @@ if [ $# -ne 1 ]; then
   echo ""
   exit 1
 fi
-
-UNIT_TEST=$1/unit-test
 
 # Disable permanent log for all the controls we are going to run in here
 
@@ -46,7 +48,10 @@ ip link del dev "$IFACE1" &> /dev/null # Just in case
 # (Re-)create veth virtual network devices
 
 # create namespaces
-ip netns add "$IFACE0" || exit $?
+if ! ip netns add "$IFACE0"; then
+  echo "Failed to create netns. Insufficient capabilities?" >&2
+  exit 0
+fi
 ip netns add "$IFACE1" || exit $?
 
 # create pair of connected interfaces
@@ -54,6 +59,9 @@ ip link add dev "$IFACE0"       \
             type veth           \
             peer name "$IFACE1" \
   || exit $?
+
+IFACE0_IDX="$(ip -json a s $IFACE0 | jq '.[0].ifindex')"
+IFACE1_IDX="$(ip -json a s $IFACE1 | jq '.[0].ifindex')"
 
 # add MAC addresses
 ip link set dev "$IFACE0" address "$IFACE0_MAC" || exit $?
@@ -72,20 +80,36 @@ ip netns exec "$IFACE0" ip link set dev "$IFACE0" up || exit $?
 ip netns exec "$IFACE1" ip link set dev "$IFACE1" up || exit $?
 
 # add routes
-ip netns exec "$IFACE0" ip route add unicast 192.168.36.0/24 dev "$IFACE0"
-ip netns exec "$IFACE0" ip route add unicast default via 192.168.42.11 dev "$IFACE0"
+ip netns exec "$IFACE0" ip route add unicast 192.168.36.0/24 dev "$IFACE0" || exit $?
+ip netns exec "$IFACE0" ip route add unicast default via 192.168.42.11 dev "$IFACE0" || exit $?
 
 # dump routes
 echo dump route:
-ip netns exec "$IFACE0" ip route
+ip netns exec "$IFACE0" ip route || exit $?
 echo done
 
 # ping to get ARP entry
-ip netns exec "$IFACE0" ping -c1 "${IFACE1_ADDR}"
-sleep "0.15s"
+ip netns exec "$IFACE0" ping -c1 "${IFACE1_ADDR}" || exit $?
+sleep "0.15s" || exit $?
 
 # run test in namespace "$IFACE0"
-ip netns exec "$IFACE0" $UNIT_TEST/test_ip || exit $?
+ACTUAL="$(ip netns exec "$IFACE0" $UNIT_TEST/test_ip_dump)" || exit $?
+
+set +x
+read -r -d '' EXPECTED <<EOF
+ARP table:
+  192.168. 42. 11  40:00:00:80:00:f1  $(printf '%2u' $IFACE0_IDX)  1d
+Routing table:
+  192.168. 42. 11    0.  0.  0.  0    0.  0.  0.  0   0    0.  0.  0.  0  $(printf '%2u' $IFACE0_IDX)  51
+    0.  0.  0.  0  192.168. 36.  0  255.255.255.  0  24    0.  0.  0.  0  $(printf '%2u' $IFACE0_IDX)  4d
+    0.  0.  0.  0  192.168. 42.  0  255.255.255.  0  24  192.168. 42. 10  $(printf '%2u' $IFACE0_IDX)  6d
+EOF
+
+if [[ "$ACTUAL" != "$EXPECTED" ]]; then
+  echo "Unexpected output" >&2
+  exit 1
+fi
+set -x
 
 # TODO verify output of previous command, or possibly
 #      change it to do verification internally
